title: Github Pages Tutorial Project
author: neepher
email: lou_yj@aliyun.com
description: > # this means to ignore newlines until "baseurl:"
  This is the course of Github pages.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  neepher

show_excerpts: true # set to false to remove excerpts on the homepage

# change the theme of this page
theme: minima
